--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5 (Debian 17.5-1.pgdg120+1)
-- Dumped by pg_dump version 17.5 (Debian 17.5-1.pgdg120+1)

-- Started on 2025-07-23 15:09:33 UTC

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16390)
-- Name: sketch; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sketch (
    sketch_id integer NOT NULL,
    concept character varying NOT NULL,
    model_json json NOT NULL,
    model_name character varying NOT NULL,
    create_time timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.sketch OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16389)
-- Name: sketch_sketch_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sketch ALTER COLUMN sketch_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sketch_sketch_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3362 (class 0 OID 16390)
-- Dependencies: 218
-- Data for Name: sketch; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.sketch VALUES (17, 'giraffe', '{"answer": {"concept": "Giraffe", "strokes": {"s1": {"points": "''x20y20'', ''x28y22'', ''x30y18'', ''x28y14'', ''x20y12'', ''x12y14'', ''x10y18'', ''x12y22'', ''x20y20''", "t_values": "0.00, 0.125, 0.25, 0.375, 0.50, 0.625, 0.75, 0.875, 1.00", "id": "giraffe body oval"}, "s2": {"points": "''x22y22'', ''x23y28'', ''x24y35'', ''x25y40''", "t_values": "0.00, 0.33, 0.66, 1.00", "id": "giraffe neck"}, "s3": {"points": "''x23y40'', ''x27y42'', ''x27y45'', ''x23y47'', ''x19y45'', ''x19y42'', ''x23y40''", "t_values": "0.00, 0.16, 0.33, 0.50, 0.66, 0.83, 1.00", "id": "giraffe head"}, "s4": {"points": "''x15y14'', ''x14y8'', ''x13y3''", "t_values": "0.00, 0.50, 1.00", "id": "front left leg"}, "s5": {"points": "''x19y14'', ''x18y8'', ''x17y3''", "t_values": "0.00, 0.50, 1.00", "id": "front right leg"}, "s6": {"points": "''x21y14'', ''x22y8'', ''x23y3''", "t_values": "0.00, 0.50, 1.00", "id": "back left leg"}, "s7": {"points": "''x25y14'', ''x26y8'', ''x27y3''", "t_values": "0.00, 0.50, 1.00", "id": "back right leg"}, "s8": {"points": "''x28y16'', ''x32y14'', ''x35y12''", "t_values": "0.00, 0.50, 1.00", "id": "giraffe tail"}, "s9": {"points": "''x21y46''", "t_values": "0.00", "id": "left horn"}, "s10": {"points": "''x25y46''", "t_values": "0.00", "id": "right horn"}}}}', 'claude-sonnet-4-20250514', '2025-07-08 12:44:16.425328');
INSERT INTO public.sketch VALUES (18, 'monkey', '{"answer": {"concept": "Monkey", "strokes": {"s1": {"points": "''x25y42'', ''x32y39'', ''x35y35'', ''x32y31'', ''x25y28'', ''x18y31'', ''x15y35'', ''x18y39'', ''x25y42''", "t_values": "0.00, 0.125, 0.25, 0.375, 0.50, 0.625, 0.75, 0.875, 1.00", "id": "monkey head circle"}, "s2": {"points": "''x15y38'', ''x12y40'', ''x10y38'', ''x12y36'', ''x15y38''", "t_values": "0.00, 0.25, 0.50, 0.75, 1.00", "id": "left ear"}, "s3": {"points": "''x35y38'', ''x38y40'', ''x40y38'', ''x38y36'', ''x35y38''", "t_values": "0.00, 0.25, 0.50, 0.75, 1.00", "id": "right ear"}, "s4": {"points": "''x22y36''", "t_values": "0.00", "id": "left eye"}, "s5": {"points": "''x28y36''", "t_values": "0.00", "id": "right eye"}, "s6": {"points": "''x25y33''", "t_values": "0.00", "id": "nose"}, "s7": {"points": "''x23y31'', ''x25y30'', ''x27y31''", "t_values": "0.00, 0.50, 1.00", "id": "mouth"}, "s8": {"points": "''x25y28'', ''x28y25'', ''x30y20'', ''x28y15'', ''x25y12'', ''x22y15'', ''x20y20'', ''x22y25'', ''x25y28''", "t_values": "0.00, 0.125, 0.25, 0.375, 0.50, 0.625, 0.75, 0.875, 1.00", "id": "monkey body"}, "s9": {"points": "''x20y22'', ''x15y24'', ''x12y22'', ''x15y20''", "t_values": "0.00, 0.33, 0.67, 1.00", "id": "left arm"}, "s10": {"points": "''x30y22'', ''x35y24'', ''x38y22'', ''x35y20''", "t_values": "0.00, 0.33, 0.67, 1.00", "id": "right arm"}, "s11": {"points": "''x22y12'', ''x20y8'', ''x22y5''", "t_values": "0.00, 0.50, 1.00", "id": "left leg"}, "s12": {"points": "''x28y12'', ''x30y8'', ''x28y5''", "t_values": "0.00, 0.50, 1.00", "id": "right leg"}, "s13": {"points": "''x30y18'', ''x35y16'', ''x40y18'', ''x42y22''", "t_values": "0.00, 0.33, 0.67, 1.00", "id": "tail"}}}}', 'claude-sonnet-4-20250514', '2025-07-08 13:56:00.39891');
INSERT INTO public.sketch VALUES (19, 'banana', '{"answer": {"concept": "Banana", "strokes": {"s1": {"points": "''x15y35'', ''x20y32'', ''x28y28'', ''x35y25'', ''x40y22''", "t_values": "0.00, 0.25, 0.50, 0.75, 1.00", "id": "banana top curve"}, "s2": {"points": "''x15y35'', ''x18y30'', ''x25y24'', ''x32y20'', ''x40y22''", "t_values": "0.00, 0.25, 0.50, 0.75, 1.00", "id": "banana bottom curve"}, "s3": {"points": "''x15y35'', ''x13y37'', ''x12y38''", "t_values": "0.00, 0.50, 1.00", "id": "banana stem"}, "s4": {"points": "''x18y33'', ''x22y29'', ''x28y26'', ''x34y23''", "t_values": "0.00, 0.33, 0.66, 1.00", "id": "peel line 1"}, "s5": {"points": "''x20y32'', ''x24y28'', ''x30y25'', ''x36y23''", "t_values": "0.00, 0.33, 0.66, 1.00", "id": "peel line 2"}, "s6": {"points": "''x22y31'', ''x26y27'', ''x32y24'', ''x38y22''", "t_values": "0.00, 0.33, 0.66, 1.00", "id": "peel line 3"}}}}', 'claude-sonnet-4-20250514', '2025-07-08 13:56:16.982298');
INSERT INTO public.sketch VALUES (20, 'speaker', '{"answer": {"concept": "Speaker", "strokes": {"s1": {"points": "''x15y40'', ''x35y40'', ''x35y40'', ''x35y15'', ''x35y15'', ''x15y15'', ''x15y15'', ''x15y40''", "t_values": "0.00,0.25,0.25,0.50,0.50,0.75,0.75,1.00", "id": "main speaker cabinet rectangle"}, "s2": {"points": "''x25y32'', ''x31y30'', ''x33y25'', ''x31y20'', ''x25y18'', ''x19y20'', ''x17y25'', ''x19y30'', ''x25y32''", "t_values": "0.00, 0.125, 0.25, 0.375, 0.50, 0.625, 0.75, 0.875, 1.00", "id": "main speaker driver circle"}, "s3": {"points": "''x25y37'', ''x28y36'', ''x29y34'', ''x28y32'', ''x25y31'', ''x22y32'', ''x21y34'', ''x22y36'', ''x25y37''", "t_values": "0.00, 0.125, 0.25, 0.375, 0.50, 0.625, 0.75, 0.875, 1.00", "id": "tweeter circle"}}}}', 'claude-sonnet-4-20250514', '2025-07-08 13:56:31.520655');
INSERT INTO public.sketch VALUES (21, 'superman', '{"answer": {"concept": "Superman", "strokes": {"s1": {"points": "''x22y40'', ''x28y42'', ''x32y40'', ''x32y36'', ''x28y34'', ''x22y34'', ''x18y36'', ''x18y40'', ''x22y40''", "t_values": "0.00, 0.125, 0.25, 0.375, 0.50, 0.625, 0.75, 0.875, 1.00", "id": "head outline"}, "s2": {"points": "''x20y34'', ''x20y20'', ''x20y20'', ''x30y20'', ''x30y20'', ''x30y34'', ''x30y34'', ''x20y34''", "t_values": "0.00, 0.3, 0.25, 0.5, 0.5, 0.75, 0.75, 1.00", "id": "torso rectangle"}, "s3": {"points": "''x22y32'', ''x25y30'', ''x28y32''", "t_values": "0.00, 0.5, 1.00", "id": "S symbol top curve"}, "s4": {"points": "''x22y28'', ''x28y28''", "t_values": "0.00, 1.00", "id": "S symbol middle line"}, "s5": {"points": "''x28y26'', ''x25y24'', ''x22y26''", "t_values": "0.00, 0.5, 1.00", "id": "S symbol bottom curve"}, "s6": {"points": "''x18y34'', ''x15y36'', ''x12y32'', ''x10y28'', ''x12y24'', ''x16y22'', ''x20y24''", "t_values": "0.00, 0.2, 0.4, 0.6, 0.8, 0.9, 1.00", "id": "cape left side"}, "s7": {"points": "''x32y34'', ''x35y36'', ''x38y32'', ''x40y28'', ''x38y24'', ''x34y22'', ''x30y24''", "t_values": "0.00, 0.2, 0.4, 0.6, 0.8, 0.9, 1.00", "id": "cape right side"}, "s8": {"points": "''x20y20'', ''x18y15'', ''x18y15'', ''x22y15'', ''x22y15'', ''x22y20''", "t_values": "0.00, 0.4, 0.35, 0.6, 0.65, 1.00", "id": "left arm"}, "s9": {"points": "''x30y20'', ''x32y15'', ''x32y15'', ''x28y15'', ''x28y15'', ''x28y20''", "t_values": "0.00, 0.4, 0.35, 0.6, 0.65, 1.00", "id": "right arm"}}}}', 'claude-sonnet-4-20250514', '2025-07-08 13:56:51.184648');
INSERT INTO public.sketch VALUES (22, 'pen-pineapple-apple-pen', '{"answer": {"concept": "Pen-Pineapple-Apple-Pen", "strokes": {"s1": {"points": "''x15y32'', ''x12y30'', ''x10y27'', ''x12y24'', ''x15y22'', ''x18y24'', ''x20y27'', ''x18y30'', ''x15y32''", "t_values": "0.00, 0.125, 0.25, 0.375, 0.50, 0.625, 0.75, 0.875, 1.00", "id": "apple body circle"}, "s2": {"points": "''x15y32'', ''x15y34''", "t_values": "0.00, 1.00", "id": "apple stem"}, "s3": {"points": "''x37y35'', ''x35y33'', ''x33y30'', ''x33y25'', ''x35y22'', ''x37y20'', ''x39y22'', ''x41y25'', ''x41y30'', ''x39y33'', ''x37y35''", "t_values": "0.00, 0.1, 0.2, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95, 1.00", "id": "pineapple body oval"}, "s4": {"points": "''x35y35'', ''x34y38'', ''x35y40''", "t_values": "0.00, 0.5, 1.00", "id": "pineapple leaf left"}, "s5": {"points": "''x37y35'', ''x37y39'', ''x37y41''", "t_values": "0.00, 0.5, 1.00", "id": "pineapple leaf center"}, "s6": {"points": "''x39y35'', ''x40y38'', ''x39y40''", "t_values": "0.00, 0.5, 1.00", "id": "pineapple leaf right"}, "s7": {"points": "''x33y28'', ''x35y26'', ''x37y28'', ''x39y26'', ''x41y28''", "t_values": "0.00, 0.25, 0.5, 0.75, 1.00", "id": "pineapple pattern line 1"}, "s8": {"points": "''x34y30'', ''x36y28'', ''x38y30'', ''x40y28''", "t_values": "0.00, 0.33, 0.66, 1.00", "id": "pineapple pattern line 2"}, "s9": {"points": "''x8y27'', ''x12y27''", "t_values": "0.00, 1.00", "id": "pen tip"}, "s10": {"points": "''x12y27'', ''x12y26'', ''x12y26'', ''x44y26'', ''x44y26'', ''x44y28'', ''x44y28'', ''x12y28'', ''x12y28'', ''x12y27''", "t_values": "0.00, 0.05, 0.1, 0.45, 0.5, 0.55, 0.9, 0.95, 0.98, 1.00", "id": "pen body cylinder"}, "s11": {"points": "''x44y26'', ''x46y27'', ''x44y28''", "t_values": "0.00, 0.5, 1.00", "id": "pen back end"}}}}', 'claude-sonnet-4-20250514', '2025-07-08 13:57:19.698747');
INSERT INTO public.sketch VALUES (23, 'Giraffe', '{"answer": {"concept": "Giraffe", "strokes": {"s1": {"points": "''x18y25'', ''x32y27'', ''x34y20'', ''x32y15'', ''x18y13'', ''x16y20'', ''x18y25''", "t_values": "0.00, 0.2, 0.35, 0.5, 0.8, 0.9, 1.00", "id": "giraffe body oval"}, "s2": {"points": "''x20y25'', ''x19y30'', ''x18y35'', ''x17y40''", "t_values": "0.00, 0.3, 0.7, 1.00", "id": "giraffe neck"}, "s3": {"points": "''x15y42'', ''x20y44'', ''x22y42'', ''x20y40'', ''x15y40'', ''x13y41'', ''x15y42''", "t_values": "0.00, 0.2, 0.35, 0.5, 0.7, 0.85, 1.00", "id": "giraffe head"}, "s4": {"points": "''x22y15'', ''x23y10'', ''x24y5''", "t_values": "0.00, 0.5, 1.00", "id": "front left leg"}, "s5": {"points": "''x26y15'', ''x27y10'', ''x28y5''", "t_values": "0.00, 0.5, 1.00", "id": "front right leg"}, "s6": {"points": "''x28y15'', ''x29y10'', ''x30y5''", "t_values": "0.00, 0.5, 1.00", "id": "back left leg"}, "s7": {"points": "''x30y15'', ''x31y10'', ''x32y5''", "t_values": "0.00, 0.5, 1.00", "id": "back right leg"}, "s8": {"points": "''x32y18'', ''x36y17'', ''x38y15''", "t_values": "0.00, 0.6, 1.00", "id": "giraffe tail"}, "s9": {"points": "''x16y44''", "t_values": "0.00", "id": "left horn"}, "s10": {"points": "''x19y44''", "t_values": "0.00", "id": "right horn"}}}}', 'claude-sonnet-4-20250514', '2025-07-10 17:04:40.380655');
INSERT INTO public.sketch VALUES (24, 'tank', '{"answer": {"concept": "Tank", "strokes": {"s1": {"points": "''x15y15'', ''x35y15'', ''x35y15'', ''x35y25'', ''x35y25'', ''x15y25'', ''x15y25'', ''x15y15''", "t_values": "0.00,0.25,0.25,0.50,0.50,0.75,0.75,1.00", "id": "tank main hull body"}, "s2": {"points": "''x20y25'', ''x32y25'', ''x32y25'', ''x32y32'', ''x32y32'', ''x20y32'', ''x20y32'', ''x20y25''", "t_values": "0.00,0.25,0.25,0.50,0.50,0.75,0.75,1.00", "id": "tank turret"}, "s3": {"points": "''x32y28'', ''x42y28''", "t_values": "0.00,1.00", "id": "tank gun barrel"}, "s4": {"points": "''x17y15'', ''x19y13'', ''x21y13'', ''x23y15'', ''x25y13'', ''x27y13'', ''x29y15'', ''x31y13'', ''x33y13'', ''x33y15''", "t_values": "0.00,0.11,0.22,0.33,0.44,0.55,0.66,0.77,0.88,1.00", "id": "tank left track wheels"}, "s5": {"points": "''x15y13'', ''x35y13''", "t_values": "0.00,1.00", "id": "tank bottom track line"}}}}', 'claude-sonnet-4-20250514', '2025-07-14 16:57:47.676884');
INSERT INTO public.sketch VALUES (25, 'elephant', '{"answer": {"concept": "Elephant", "strokes": {"s1": {"points": "''x20y25'', ''x35y28'', ''x38y20'', ''x35y12'', ''x20y10'', ''x12y12'', ''x10y20'', ''x12y28'', ''x20y25''", "t_values": "0.00, 0.125, 0.25, 0.375, 0.50, 0.625, 0.75, 0.875, 1.00", "id": "elephant main body"}, "s2": {"points": "''x15y25'', ''x22y32'', ''x25y35'', ''x22y38'', ''x15y35'', ''x8y38'', ''x5y35'', ''x8y32'', ''x15y25''", "t_values": "0.00, 0.125, 0.25, 0.375, 0.50, 0.625, 0.75, 0.875, 1.00", "id": "elephant head"}, "s3": {"points": "''x12y32'', ''x10y28'', ''x8y24'', ''x9y20'', ''x12y18''", "t_values": "0.00, 0.25, 0.50, 0.75, 1.00", "id": "elephant trunk"}, "s4": {"points": "''x8y38'', ''x3y42'', ''x2y38'', ''x3y34'', ''x8y32''", "t_values": "0.00, 0.25, 0.50, 0.75, 1.00", "id": "left ear"}, "s5": {"points": "''x22y38'', ''x27y42'', ''x28y38'', ''x27y34'', ''x22y32''", "t_values": "0.00, 0.25, 0.50, 0.75, 1.00", "id": "right ear"}, "s6": {"points": "''x14y10'', ''x14y3'', ''x14y3'', ''x17y3'', ''x17y3'', ''x17y10''", "t_values": "0.00, 0.4, 0.35, 0.6, 0.65, 1.00", "id": "front left leg"}, "s7": {"points": "''x20y10'', ''x20y3'', ''x20y3'', ''x23y3'', ''x23y3'', ''x23y10''", "t_values": "0.00, 0.4, 0.35, 0.6, 0.65, 1.00", "id": "front right leg"}, "s8": {"points": "''x26y10'', ''x26y3'', ''x26y3'', ''x29y3'', ''x29y3'', ''x29y10''", "t_values": "0.00, 0.4, 0.35, 0.6, 0.65, 1.00", "id": "back left leg"}, "s9": {"points": "''x32y10'', ''x32y3'', ''x32y3'', ''x35y3'', ''x35y3'', ''x35y10''", "t_values": "0.00, 0.4, 0.35, 0.6, 0.65, 1.00", "id": "back right leg"}, "s10": {"points": "''x35y18'', ''x40y16'', ''x42y18''", "t_values": "0.00, 0.50, 1.00", "id": "tail"}, "s11": {"points": "''x12y35''", "t_values": "0.00", "id": "eye"}}}}', 'claude-sonnet-4-20250514', '2025-07-20 08:20:25.531108');
INSERT INTO public.sketch VALUES (26, 'cat', '{"answer": {"concept": "Cat", "strokes": {"s1": {"points": "''x20y38'', ''x25y42'', ''x30y38'', ''x32y33'', ''x30y28'', ''x25y26'', ''x20y28'', ''x18y33'', ''x20y38''", "t_values": "0.00, 0.125, 0.25, 0.375, 0.50, 0.625, 0.75, 0.875, 1.00", "id": "cat head outline"}, "s2": {"points": "''x22y40'', ''x25y45'', ''x25y45'', ''x22y40''", "t_values": "0.00, 0.5, 0.5, 1.00", "id": "left ear"}, "s3": {"points": "''x28y40'', ''x25y45'', ''x25y45'', ''x28y40''", "t_values": "0.00, 0.5, 0.5, 1.00", "id": "right ear"}, "s4": {"points": "''x22y35'', ''x24y37'', ''x26y35'', ''x24y33'', ''x22y35''", "t_values": "0.00, 0.25, 0.50, 0.75, 1.00", "id": "left eye"}, "s5": {"points": "''x28y35'', ''x26y37'', ''x24y35'', ''x26y33'', ''x28y35''", "t_values": "0.00, 0.25, 0.50, 0.75, 1.00", "id": "right eye"}, "s6": {"points": "''x24y32'', ''x25y31'', ''x25y31'', ''x26y32''", "t_values": "0.00, 0.5, 0.5, 1.00", "id": "nose"}, "s7": {"points": "''x25y31'', ''x23y29''", "t_values": "0.00, 1.00", "id": "left mouth line"}, "s8": {"points": "''x25y31'', ''x27y29''", "t_values": "0.00, 1.00", "id": "right mouth line"}}}}', 'claude-sonnet-4-20250514', '2025-07-20 12:28:42.487641');


--
-- TOC entry 3368 (class 0 OID 0)
-- Dependencies: 217
-- Name: sketch_sketch_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.sketch_sketch_id_seq', 27, true);


--
-- TOC entry 3213 (class 2606 OID 16397)
-- Name: sketch sketch_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sketch
    ADD CONSTRAINT sketch_pk PRIMARY KEY (sketch_id);


--
-- TOC entry 3215 (class 2606 OID 16405)
-- Name: sketch sketch_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sketch
    ADD CONSTRAINT sketch_unique UNIQUE (concept);


--
-- TOC entry 2044 (class 826 OID 16402)
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT,INSERT ON TABLES TO myuser;


-- Completed on 2025-07-23 15:09:33 UTC

--
-- PostgreSQL database dump complete
--

