FROM python:3.11

WORKDIR /usr/src/app

COPY . .

RUN pip install -e .

EXPOSE 8000

# ARG USERNAME=mos
# RUN usermod --login ${USERNAME} --move-home --home /home/${USERNAME} vscode && \
#     groupmod --new-name ${USERNAME} vscode


CMD ["python", "app.py"]
