[project]
name = "chatdraw"
version = "0.1.0"
description = ""
authors = [{ name="Moshe", email="barboym@gmail.com" }]
dependencies = [
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["chatdraw"]
