
name: Draw Service Test

on:
  push:
    paths:
      - 'draw_service/**'
      - '.github/workflows/draw_service-test.yaml'

jobs:
  test-draw-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: draw_service
    steps:
      - name: Create a local Postgres DB
        uses: ikalnytskyi/action-setup-postgres@v7
        with:
          username: postgres
          password: postgres
          database: postgres
          port: 5432
          postgres-version: "17"
        id: postgres

 

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        run: uv run pytest tests
