
name: Push Backend

on:
  push:
    paths-ignore:
      - 'frontend/**'
      - '.*/**'
      - 'dist/**'
      

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: cache-pip-dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip

      - name: Install dependencies
        if: steps.cache-pip-dependencies.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Run tests
        run: |
          if [ -f pytest.ini ] || [ -d tests ]; then pytest; fi

