
name: Draw Service Build

on:
  workflow_run:
    workflows: ["Draw Service Test"] 
    types: [completed] 
    branches: main 


jobs:
  build-draw-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: draw_service
    steps:
      - name: Checkout code  
        uses: actions/checkout@v4

      - name: login docker hub
        run: docker login -u ${{secrets.DOCKER_HUB_USER}} -p ${{secrets.DOCKER_HUB_TOKEN}}

      - name: build image
        run: docker build . -t ${{secrets.DOCKER_HUB_USER}}/chatdraw:latest
      
      - name: push image to docker hub
        run: docker push ${{secrets.DOCKER_HUB_USER}}/chatdraw:latest

