## Copilot generated:
# create github actions workflow that:
# - works on pushs and merges to main where there are changes in the frontend directory.
# - create the environent that can run vitest on the code
# - if some tests don't pass blocks the merge to main.
# - builds the frontend


name: Frontend Tests

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [main]
    paths:
      - 'frontend/**'

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run Vite tests
        run: npm run test:unit

      - name: Build frontend
        run: npm run build

